### ISSUE TITLE
Anything with {id,type} should be recoverable by vault.get(..)

### ISSUE THREAD

**Issue by tomcrane** [IIIF-Commons/vault#5]
_This is one of a few issues raised by experimenting with vault for this: https://tomcrane.github.io/scratch/cp/tree.html_

In making that demo I found that some resources can be obtained by vault.get but others cannot. For example, this seems to be true for objects that are members of arrays, but not all arrays - it doesn't happen for Canvases. If an object is a member of an array, retrieving it via vault.get({id, type}) just returns the ref not the object. I'm having to walk up the tree, obtain the parent object, get the property whose value is the array, then re-find the object in that array.

Even if Vault doesn't do any special normalisation on a resource, I don't necessarily know that.

**Comment by tomcrane** [comment]
> Since it will either de-reference it, or return what you passed it.

This wasn't all that intuitive - it took me a while to work out what was happening because I always got something back even if the ref isn't in Vault's store, so I assumed to had the full object.

On the way down the tree, this line never **_reduced_** the amount of information, because for calls where it would I had the full object in hand (e.g., as a property of an object I'm iterating over), it gave me back what I'd passed in if Vault has no entry for it:

```
iiifResource = vault.get(iiifResource);
```
https://github.com/tomcrane/scratch/blob/eded1f7314a6e0b3f3e1427fd41ab49eefb3a222/cp/tree.html#L159

But what is apparently the same call when clicking on a tree node always returns something - but for some things it's just the ref. So I had to test:

https://github.com/tomcrane/scratch/blob/eded1f7314a6e0b3f3e1427fd41ab49eefb3a222/cp/tree.html#L345

**Comment by stephenwf** [comment]
I think the `fromRef()` used to return `null` or similar if it could not find it in the Vault. If I remember, this broke sometimes when writing UIs for resources that you'd fetch - like Annotation Pages or Manifests. The UI might look like:
```js
const page = vault.get(annoPageRef);

if (!vault.requestStatus(page.id)) {
  vault.load(page.id);
}

if (page.items) {
  // render thing..
}
```

So the value of `page` enhances over time from a ref (from the returned self) to the vault-returned object.
